version: '2'
services:
  db:
    image: mysql:5.7
    ports:
          - "3336:3306"
    container_name: endorphina_db
    restart: always
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=endorphina
      - MYSQL_USER=endorphina
      - MYSQL_PASSWORD=123qwe
    command: mysqld --disable-partition-engine-check --character-set-server=utf8 --collation-server=utf8_unicode_ci 
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'